import pathlib

DATA_DIRECTORY = pathlib.Path.home() / "data"
LOG_FILE_PATH = DATA_DIRECTORY / "log.txt"
ACTIONS_DIRECTORY = DATA_DIRECTORY / "actions"
SCREENSHOTS_DIRECTORY = DATA_DIRECTORY / "screenshots"
TRAINING_DATA_DIRECTORY = DATA_DIRECTORY / "training_data"
MODEL_PATH = DATA_DIRECTORY / "vit.pd"
